項目の日本語化・表示非表示の処理追加
takamatsu-city/maps.takamatsu-fact.com pull request #113
Opened 2023-10-20 03:00 UTC by sugama-satsuki

2023-10-20 03:41 UTC, keichan34 requested changes
なるほど。もうちょっと整理しましょうか。

変換のところ、
```
const translationMap: { [key: string]: { [key: string]: string } } = {
  '大字界': {
    'meisho': '名称',
...

const propertyMap = translationMap[item.properties['class']];
for (const [prop, propJa] of Object.entities(propertyMap)) {
  delete Object.assign(items.properties,{[propJa]: items.properties[prop]})[prop];
```

で省略可できると思います。

非表示項目は単純な配列で管理してforループ内でdeleteすればいいと思います

修正よろしくお願いします :bow:

2023-10-23 05:13 UTC, keichan34 requested changes
確認よろしくお願いします

2023-10-23 05:13 UTC, keichan34 commented on src/utils/visibilityConversion.ts
> +      '主要な経過':'主要な経過',
見つからなかったときにそのままパススルーするようにすると、このマップが不要になるかと思います

2023-10-23 05:13 UTC, keichan34 commented on src/utils/visibilityConversion.ts
> +      '名称': 'name',
あれ、上記の方が `'英字': '日本語'` になってるけどここは`'日本語': '英字'` になってる。どちらかというと、 AからBのマップングを行うので、Aが左側でBが右側に統一しましょう。

2023-10-23 06:15 UTC, sugama-satsuki commented
@keichan34 
ご確認、ご指摘ありがとうございます🙇‍♀️
キー・バーリューを逆に作成していた事と、不要箇所に気づき修正加えました💦
お手数ですが、ご確認お願いします🙇‍♀️

2023-10-24 07:53 UTC, keichan34 approved these changes
とりあえずこの形で大丈夫かなと思います。
そのうち、設定ファイルに切り分けて静的なJSONとかで表現できるようにしたいです。。

2023-11-06 00:00 UTC, merged