衛生画像レイヤーを追加
takamatsu-city/maps.takamatsu-fact.com pull request #136
Opened 2024-04-16 06:46 UTC by sugama-satsuki

2024-04-16 07:06 UTC, keichan34 requested changes

2024-04-16 07:06 UTC, keichan34 commented on src/MainMap.tsx
> +            console.log(definitionId, isSelected)
console.logの削除をお願いします

2024-04-16 07:21 UTC, naogify commented
@sugama-satsuki 
細かいですが「衛生」→「衛星」に修正お願いしても良いでしょうか？

2024-04-17 02:56 UTC, keichan34 approved these changes

2024-04-18 00:34 UTC, merged