サードパーティーの表示非表示を修正
takamatsu-city/maps.takamatsu-fact.com pull request #161
Opened 2024-07-17 00:10 UTC by sugama-satsuki

2024-07-17 03:06 UTC, keichan34 requested changes
すみません、 catalog 周りのリファクタリングをお願いしますー。 thirdPartyCatalog の型や扱う関数などを分けたほうが良さそうと思いまして。。

2024-07-17 03:06 UTC, keichan34 commented on src/MainMap.tsx
> +        const definition = data as CatalogDataItem;
これはなんで必要なんだろうと思ったんですが、thirdPartyCatalog にも使うためなんですね。。なるほど。
最初、generic type でなんとかできるのかなと思ったんだけど（ `walkCategories<CatalogDataItem>` みたいな記述、定義するときは `function func<T>(input: T[]) { ... } `みたいなやつ ）けど、そうすると必要以上に複雑に何そうなので、これってもしかしたらシンプルに、 walkCategories をコピペして、CatalogDataItem で使う walkCategories はそのままで、 thirdPartyの場合は walkThirdPartyCategories の別関数を使ったほうがいいかと思います。

たまにやむおえず `data as Type` で型上書きをしないといけないけど、バグの原因にもなる（思った通りの型ではなくて本当は違う型が入ってしまったとか）ので、極力少なく使いたいと思っていますー。

2024-07-17 08:04 UTC, sugama-satsuki commented
@keichan34 
すみません、修正遅くなりました🙇‍♀️
お手数ですがご確認お願いします💦

2024-07-17 22:16 UTC, sugama-satsuki commented
@keichan34 
ご指摘ありがとうございます🙇‍♀️
度々すみません💦
修正完了しましたので再度ご確認お願いします🙇‍♀️

2024-07-17 22:28 UTC, keichan34 requested changes
細かいですが、 isThirdParty の述語関数を作ってみてください :bow:

2024-07-17 22:28 UTC, keichan34 commented on src/Sidebar.tsx
> +  const isThirdParty = item.id.includes('thirdParty');
細かいですが、TypeScriptで「この変数はこの型だ」と評価するのは、

```typescript
function isThirdParty(item: ThirdPartyCatalogItem | CatalogItem): item is ThirdPartyCatalogItem {
  return item.id.startsWith('thirdParty/');
}
```

このようなヘルパーの関数は多分他の場所でも使うので、 thirdPartyCatalog.ts に入れると便利かもしれない。

こうすると、 `item as ...` は使わなくても良くなるはず
例に includes('thirdParty') から startsWith('thirdParty/') に変更しましたが、こちらは例えば普通のカタログに入っているはずのものがthirdPartyの文字列が入っているとバグってしまうので、より特定した表現に変えたもの。

2024-07-17 23:42 UTC, sugama-satsuki commented
@keichan34 
すみません、こちら作成しました🙇‍♀️
お手隙でご確認お願いします！

2024-07-18 01:06 UTC, keichan34 commented on src/Sidebar.tsx
>      if(isThirdParty) {
ここで

```typescript
if (isThirdPartyItem(item) && 'items' in item) {
  return [...walkThirdPartyCategories(item.items)].map(x => x.shortId);
```
で行けるかなと思いますが、試してもらってもいいですか :bow:

2024-07-18 01:29 UTC, sugama-satsuki commented
@keichan34 
以下でCategoryとして受け取る型指定しているので、itemsがあるかどうかのチェックはしなくても大丈夫でした🙆‍♀️
https://github.com/takamatsu-city/maps.takamatsu-fact.com/blob/4552ad1b88437d81b3295ea296db49b4d0d196ff/src/Sidebar.tsx#L18

asなしで大丈夫でした🙇‍♀️

2024-07-18 01:30 UTC, keichan34 approved these changes
なるほど！ありがとうございました！

2024-07-18 02:21 UTC, merged