スマートフォンでの閲覧に対応
takamatsu-city/maps.takamatsu-fact.com pull request #83
Opened 2023-06-28 08:08 UTC by naogify

Close #62

2023-06-30 02:46 UTC, keichan34 requested changes
React は基本的には declarative 方式でスタイリングしましょう

動きでもう一つ修正してほしいところもありますが、画面が細い状態でデータ一覧を一旦隠すと、画面の幅を広げると表示できなくなってしまう。 media query でis-openクラスを無視するようにするとか、できないかな？

2023-06-30 02:46 UTC, keichan34 commented on src/Sidebar.tsx
> +    <div ref={sidebarRef} className='sidebar'>
class で対応しましょう

```
className={classNames('sidebar', {'sidebar-open': isOpenedSidebar})}
```

2023-07-04 08:17 UTC, naogify commented on src/Sidebar.tsx
> +    <div ref={sidebarRef} className='sidebar'>
@keichan34 
こちらの件修正しました。お手すきの時に確認お願いしても良いでしょうか？

2023-07-06 01:53 UTC, keichan34 approved these changes

2023-07-07 01:35 UTC, naogify commented
@takamatsu-toshiseibi 
お世話になっております。Geolonia の大橋です。
スマートフォンでの閲覧時にデータを選択するリストを下部から出し入れできるように修正しました。問題ないようでしたら本番環境に反映しますので、お教えください。

プレビューURL
https://deploy-preview-83--map-takamatsu-fact-com.netlify.app/


<img width="430" alt="スクリーンショット 2023-07-07 10 35 02" src="https://github.com/takamatsu-city/maps.takamatsu-fact.com/assets/8760841/b289f4bb-1d33-4a54-82fb-af9db4f3d4f5">

2023-07-26 08:45 UTC, merged